apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pjm3ddmvf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pjm3ddmvf-go 
  name: pjm3ddmvf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pjm3ddmvf-go 
